[build]
  base = "frontend/chat-app"  # Path to the frontend directory
  publish = "frontend/chat-app/build"  # Path to the build folder in frontend
  command = "npm run build"  # Command to run the build process

[build.environment]
  NODE_ENV = "production"  # Make sure to set the correct Node environment
  CI = "false"  # Disable CI flag to avoid treating warnings as errors
