[build]
  base = "frontend/chat-app"  # Path to frontend directory
  publish = "build"           # Path to build folder inside the frontend
  command = "npm run build"   # Build command

[build.environment]
  NODE_ENV = "production"
  CI = "false"                # Set CI to false to avoid warnings as errors
